name: Deploy to Dropbox

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'  # Adjust version as necessary

      - name: Install dependencies
        run: npm install axios

      - name: Run script to create folders
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          node script.js
